# ESTO ES UN SCRIPT DE PRUEBA
# POR FAVOR, PONER SU NOMBRE COMO COMENTARIO
# LUEGO HACER COMMIT CON UN COMENTARIO
# EN EL TERMINAL (ZONA DE LA CONSOLA)
# ESCRIBIR
git push origin main # ESTO ENVÍA LO QUE ESCRIBO A GITHUB
# CUANDO TODOS TERMINEN
git pull origin main # ESTO ACTUALIZA DE ACUERDO A LO QUE HAY EN GITHUB

#David
#Natalia 